### ISSUE TITLE
Documentation NotFound

### ISSUE THREAD

**Issue by Platonenkov** [CASL-AE/xrpl.c#10]
Hi friend, your documentation link did not work (
![image](https://user-images.githubusercontent.com/44946855/180843378-e7232228-3f46-40b4-a1e7-6b6567be27de.png)

**Comment by dangell7** [comment]
Thank you for this issue. 

We are in the process of refactoring the C# library. As soon as this is done I will update the documentation.

In the mean time the examples should work.
