### ISSUE TITLE
Offers error

### ISSUE THREAD

**Issue by Platonenkov** [CASL-AE/xrpl.c#11]
Qualitymust be double in the Offers
![image](https://user-images.githubusercontent.com/44946855/181494246-05d3c82a-7c66-4001-9c74-7a0fe557cc7c.png)

or it will be error
![image](https://user-images.githubusercontent.com/44946855/181494460-98716508-a26d-4fad-9bee-62cd61528061.png)

And if Offers called without Limit - it will `Invalid_parameter`
![image](https://user-images.githubusercontent.com/44946855/181495163-f01e5162-64c9-42c1-9ca7-2a6060953696.png)

find me please in telegram @Platonenkov, I wath to help

**Comment by dangell7** [comment]
Hey Platonenkov, 

Thank you very much for helping contribute to this repo. To start, I'm not sure we are going to add all of the parameters like that for all the functions. In both sdks it is recommended to use the `request`. So in your case, if you want to access limit and marker, you would do;

```
AccountOffersRequest offersRequest = new AccountOffersRequest(account) { Limit = 100 };
var accountOffers = await client.AccountOffers(offersRequest);
Assert.IsNotNull(accountOffers);
```

The tests are not clear, there is lacking documentation so I take responsibility for that. I will review the other changes. I'm not against adding the parameter like you did, but then we need to do it for all of them. However, for documentation/intellisense it might be better to add those connivence functions.

**Comment by Platonenkov** [comment]
>
ok but if you use `var accountOffers = await client.AccountOffers(account);` it will be server error responce
![image](https://user-images.githubusercontent.com/44946855/181599346-d1a3d6e5-6aee-4053-9f7b-255513c9f139.png)

**Comment by dangell7** [comment]
Limit is actually an optional so `public uint? Limit { get; set; }`

And Quality is a string. If you make those changes I will add the tests to PR's and we can make sure it builds and see if that works for you?

**Comment by Platonenkov** [comment]
> 
as I said
Limit in this request is mandatory
![image](https://user-images.githubusercontent.com/44946855/181602272-e75beb26-1dc6-42e8-8dd5-994a8858f835.png)
![image](https://user-images.githubusercontent.com/44946855/181602281-4e5144cb-1e4b-41a8-9863-0a377082a0f2.png)

**Comment by dangell7** [comment]
I'm not getting that error in tests and limit is an optional field as per rippled RPC/WSS. 

https://xrpl.org/websocket-api-tool.html#account_offers

So enforcing that for everyone is not the right solution.

Here is what is working in the tests, can you try this?

`AccountOffers accountOffers = await client.AccountOffers(account);`

If you can provide me the client url and the account you're using I can see if I can replicate the issue? It possible its nothing to do with the call but the casting to AccountOfferResponse.

**Comment by Platonenkov** [comment]
> I'm not getting that error in tests and limit is an optional field as per rippled RPC/WSS.
> 
> https://xrpl.org/websocket-api-tool.html#account_offers
> 
> So enforcing that for everyone is not the right solution.
> 
> Here is what is working in the tests, can you try this?
> 
> `AccountOffers accountOffers = await client.AccountOffers(account);`
> 
> If you can provide me the client url and the account you're using I can see if I can replicate the issue? It possible its nothing to do with the call but the casting to AccountOfferResponse.

In test servers with Empty wallet there are no errors, but on mainnet....

**Comment by Platonenkov** [comment]
Server `"wss://xrplcluster.com/"`
Wallet `rLiooJRSKeiNfRJcDBUhu4rcjQjGLWqa4p`

**Comment by dangell7** [comment]
Works for me. Here is what I chaged.

https://github.com/Transia-RnD/xrpl.c/pull/14/commits/2de955059358ccd8ac2c1136934ea45d010cfa93

**Comment by Platonenkov** [comment]
> Works for me. Here is what I chaged.
> 
> [2de9550](https://github.com/Transia-RnD/xrpl.c/commit/2de955059358ccd8ac2c1136934ea45d010cfa93)

works where? 
![image](https://user-images.githubusercontent.com/44946855/181690060-e271757a-f0b4-4645-a1a2-279bf6e10955.png)


but test is ok...
![image](https://user-images.githubusercontent.com/44946855/181689903-6029b097-1817-4697-bf5f-e0a1e919d98e.png)

**Comment by dangell7** [comment]
<img width="1512" alt="Screen Shot 2022-07-29 at 11 17 11 AM" src="https://user-images.githubusercontent.com/25502424/181790941-2af3ca27-526b-40cc-9155-d7595d1c48e0.png">

I will have to look deeper into this.

**Comment by Platonenkov** [comment]
https://github.com/Transia-RnD/xrpl.c/pull/23
