### ISSUE TITLE
Decimal poin error

### ISSUE THREAD

**Issue by Platonenkov** [CASL-AE/xrpl.c#13]
Decimal poin parse error
![image](https://user-images.githubusercontent.com/44946855/181607248-4fd72456-bcc1-4fae-835a-94ce3ee72654.png)

InvarianCulture as an option
![image](https://user-images.githubusercontent.com/44946855/181607623-fd4597cf-4437-44c6-b87b-0c83ce6568a6.png)

**Comment by dangell7** [comment]
Can you provide me with the code that caused this error? Or what response this was from?

**Comment by Platonenkov** [comment]
> Can you provide me with the code that caused this error? Or what response this was from?

ofcourse

```C#
var account = "rLiooJRSKeiNfRJcDBUhu4rcjQjGLWqa4p";
var server = "wss://xrplcluster.com/";
try
{
    var Client = new RippleClient(server);
    Client.Connect();
    var currencies = await Client.GatewayBalances(account);
    foreach (var currency in currencies.Assets)
    {
        var issuer = (string)currency.Name;

        foreach (var c in currency.Value)
        {
            var cur = (string)c.currency;
            var value = (string)c.value;
            var result =  new Currency() { CurrencyCode = cur.Length > 3 ? cur.FromHexString().Trim('\0') : cur, Issuer = issuer, Value = value };

            Debug.WriteLine(result.Issuer, result.CurrencyCode, result.Value, result.ValueAsNumber);

        }
    }
}
catch (Exception e)
{
    Console.WriteLine(e);
    throw;
}
```
![image](https://user-images.githubusercontent.com/44946855/181692218-049bd1cc-2a48-4d94-9a6a-56cc636be08e.png)

**Comment by Platonenkov** [comment]
and also - error when the value is very small `"1000000000000000e-96"`
![image](https://user-images.githubusercontent.com/44946855/181711041-6fc109a1-a483-4007-8a96-15c775188e22.png)

**Comment by Platonenkov** [comment]
this work
![image](https://user-images.githubusercontent.com/44946855/181713211-4731843d-3508-4d50-82bf-be09abd26547.png)

```C#

        [JsonIgnore]
        public decimal ValueAsNumber
        {
            get
            {
                if (string.IsNullOrWhiteSpace(Value))
                    return 0;
                var can_parse = decimal.TryParse(Value, NumberStyles.Float, CultureInfo.InvariantCulture, out var result);
                return !can_parse ? 0 : result;
            }
            set => Value = value.ToString(CurrencyCode == "XRP" ? "G0" : "G15", CultureInfo.InvariantCulture);
        }
       
```

![image](https://user-images.githubusercontent.com/44946855/181713287-d096537c-52b6-4f52-bfbb-dfc364d39ceb.png)

**Comment by Platonenkov** [comment]
Same problem wherever there is used decimal.Parse
![image](https://user-images.githubusercontent.com/44946855/181751017-032cca6b-85dd-4148-963d-4fa8f90c6a1b.png)

**Comment by dangell7** [comment]
Yep I see this now. I suspect its an issue deeper in the sdk as that should be formatted as a big int but in the meantime CultureInfo.InvariantCulture seems to work. 

This also works: `decimal.Parse(Value, NumberStyles.AllowExponent | NumberStyles.AllowDecimalPoint)`

**Comment by dangell7** [comment]
<img width="1512" alt="Screen Shot 2022-07-29 at 11 27 01 AM" src="https://user-images.githubusercontent.com/25502424/181792825-1b92f7bb-7de6-4948-8c56-f009b62c8fb9.png">

Also I do not get this error. Is there another account you are using?

**Comment by Platonenkov** [comment]
> Yep I see this now. I suspect its an issue deeper in the sdk as that should be formatted as a big int but in the meantime CultureInfo.InvariantCulture seems to work.
> 
> This also works: `decimal.Parse(Value, NumberStyles.AllowExponent | NumberStyles.AllowDecimalPoint)`

I use Server `wss://xrplcluster.com/` account `rLiooJRSKeiNfRJcDBUhu4rcjQjGLWqa4p`
try it with a very small value of NFT xls14d 
![image](https://user-images.githubusercontent.com/44946855/181877219-d5bb63b6-dce3-48e5-8308-64341d28887a.png)

it will error without Culture `CultureInfo.InvariantCulture`
![image](https://user-images.githubusercontent.com/44946855/181877492-7171c719-f7ad-4c06-abeb-7acd8bb5d7eb.png)

you do not have an error because the culture installed in your computer by default is different from my region

**Comment by Andrewkasko** [comment]
Assuming the "CultureInfo" isnt affecting anything, from what I understand you can not pass a string that contains a scientific notation such as "1000000000000000e-96" to the decimal.Parse function. When I passed "0.000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000" instead of the scientific notation it returned the minimum value for a decimal which is 28 zeros after the decimal. 

Regarding the error with the value "1454.045915968565" I parsed it tp decimal.Parse() in this C# playground (https://dotnetfiddle.net/) and didnt get an error. Which makes me think it might have something to do with "CultureInfo" or something else in the SDK.

**Comment by Platonenkov** [comment]
Usually programmers do not think about regional standards. And subsequently, culture can bring a lot of mistakes when launching the application in other countries.
An example of culture behavior can be viewed in this project: [CultureInfoExplorer](https://github.com/AndreyAkinshin/CultureInfoExplorer)

![image](https://user-images.githubusercontent.com/44946855/182076343-1ad4b608-d293-44b9-ab39-07acc4258fb9.png)

![image](https://user-images.githubusercontent.com/44946855/182076721-3265e1c2-b63e-4f87-8979-683e2831b582.png)
![image](https://user-images.githubusercontent.com/44946855/182076724-f701f3f2-5680-49cb-bdf4-8a621cc35df3.png)
![image](https://user-images.githubusercontent.com/44946855/182076731-9328bf0b-a18a-4876-8a21-1e937e1d71c8.png)

**Comment by Platonenkov** [comment]
https://github.com/Transia-RnD/xrpl.c/pull/23
