### ISSUE TITLE
Hex memo decode method

### ISSUE THREAD

**Issue by Platonenkov** [CASL-AE/xrpl.c#15]
decoding Memo messages goes with incorrect encoding.

your basic method:
![image](https://user-images.githubusercontent.com/44946855/182036903-7d42193f-2144-4d54-a90c-ca0db1c3cd32.png)

after adaptation:
![image](https://user-images.githubusercontent.com/44946855/182036908-73a82c94-552a-4b95-89a1-de9931816e46.png)

```C#
        /// <summary> Memo string With smiles </summary>
        public static string MemoHexWithSmyles(string hex)
        {
            var buffer = new byte[hex.Length / 2];
            for (int i = 0; i < hex.Length; i += 2)
            {
                string hexdec = hex.Substring(i, 2);
                buffer[i / 2] = byte.Parse(hexdec, NumberStyles.HexNumber);
            }
            return Encoding.UTF8.GetString(buffer);//we could even have passed this encoding in for greater flexibility.
        }

```
Transaction hash as a sample
`8A51DDDD11CA13F2A370EDDB1B3B66DAB195B42FD1ABA6B613A08729C07ECB5F`

**Comment by Platonenkov** [comment]
why you use ASII whe hex decode? 
why not UTF8
![image](https://user-images.githubusercontent.com/44946855/182565795-ba817ceb-e4b8-4145-9c4d-703463a8cc2a.png)

**Comment by Platonenkov** [comment]
Look to DOC here
![image](https://user-images.githubusercontent.com/44946855/182769209-ae1173d6-3b6d-4d56-b934-49d5083b6277.png)

https://xrpl-py.readthedocs.io/en/stable/source/xrpl.utils.html

**Comment by dangell7** [comment]
Yes, you are correct and I was wrong. 

https://github.com/XRPLF/xrpl.js/blob/main/packages/xrpl/src/utils/stringConversion.ts

**Comment by dangell7** [comment]
Are you going to create a PR?

**Comment by Platonenkov** [comment]
> Are you going to create a PR?

https://github.com/Transia-RnD/xrpl.c/pull/23

**Comment by Platonenkov** [comment]
https://github.com/Transia-RnD/xrpl.c/pull/23
