### ISSUE TITLE
JsonSerializationException

### ISSUE THREAD

**Issue by Platonenkov** [CASL-AE/xrpl.c#16]
Newtonsoft.Json.JsonSerializationException: "Error converting value "Ticket" to type 'xrpl_c.Xrpl.Client.Model.Enums.LedgerEntryType'. Path 'transactions[61].meta.AffectedNodes[4].DeletedNode.LedgerEntryType', line 12005, position 41."

![image](https://user-images.githubusercontent.com/44946855/182455339-659b52d4-6a75-4ab2-a9ab-8b247952564a.png)
```
            var account = "rKpHiZ2y4MnvAqK2PeFeLC9k1NydJYy9TZ";
            var server = "wss://xrplcluster.com/";
```
time to time I have this message from server [ Error.txt.txt](https://github.com/Transia-RnD/xrpl.c/files/9245127/Error.txt.txt)

**Comment by Platonenkov** [comment]
no transaction of type TicketCreate

**Comment by Platonenkov** [comment]
the only thing I didn't understand is what format Memo was written in.
I couldn't decode it, but bithomp can
Transaction hash: `29300D23E92B3DAA5CB48B836BA91676C15BF35074B125280E9C8666017BCB46`
my decode from hex:
![image](https://user-images.githubusercontent.com/44946855/182533350-0c5d36c1-f3ae-4c64-bac5-e75488b87aa0.png)

bithomp
![image](https://user-images.githubusercontent.com/44946855/182533417-f014d1cd-0929-4f6e-a333-d64f5d618b8f.png)


Memo:
```
2265794A68624763694F694A46557A49314E694973496E523563434936496B705856434A392E65794A7063334E315A5849694F694A795A6B745253466C54654739714E553155523359785155357A6548417956484E4754564E4C4E7A684D563346524969776959335679636D567559336B694F6949774D6A4D774D7A45314D545A454E5445304F44637A4E4555304E6A55304D7A497A4F544D354D7A497A4D7A41774D4441774D44417749697769635856766447566659335679636D567559336B694F6949314D7A52474E454D30526A41774D4441774D4441774D4441774D4441774D4441774D4441774D4441774D4441774D4441774D44417749697769635856766447566661584E7A64575679496A6F69636E4E7654473879557A46726155646C51324E754E6D684456566857636B4E775230315854484A53636B786165694973496E46316233526C583246746233567564434936496A593149697769633246735A56397A5A5846315A57356A5A5349364E6A63784E4449354E7A6773496D6C68644349364D5459314E7A677A4D6A63314D43776961584E7A496A6F69553239736232646C626D6C6A49455A766457356B595852706232346966512E5F31644D527657706251755A6E737A6970353047544942744565762D79657741676577516B304F353130334155316E4C6D325674745662335844574A62594A4B3555576D45422D4D7150304571434C6E684962784E6722
```

**Comment by dangell7** [comment]
Its a jwt token.

**Comment by Platonenkov** [comment]
> Its a jwt token.

but how bithomp decode this to Memo?
![image](https://user-images.githubusercontent.com/44946855/182554759-c37bde20-0c87-4774-af33-dd4ff77ae8ca.png)

**Comment by dangell7** [comment]
Something like. https://pyjwt.readthedocs.io/en/stable/. I don't know the compatible in C#.

**Comment by Platonenkov** [comment]
YES, THANK YOU!
![image](https://user-images.githubusercontent.com/44946855/182558638-3b5a40b9-143c-458f-acf2-da8a7fe8de46.png)

JWT is transmitted only in ticket requests or in some other? didn't come across?

**Comment by dangell7** [comment]
I think it's more that user was using in the memo. Interesting find though
