### ISSUE TITLE
delete trustline Question

### ISSUE THREAD

**Issue by Platonenkov** [CASL-AE/xrpl.c#20]
Help me please, how to delete trustline?
I found this note:
```
To remove a trust line, reset it to its default state. (0 limit, 0 balance, and no non-default settings.)
```

what is `non-default settings` ?

now I use this request:
```C#
 var accountInfo = await Client.AccountInfo(AccountSender);

            ITrustSetTransaction trustSet = new TrustSetTransaction()
            {
                Account = AccountSender,
                Flags = TrustSetFlags.tfSetNoRipple,
                TransactionType = TransactionType.TrustSet,
                LimitAmount = new Currency { Value = "0", Issuer = Issuer, CurrencyCode = CurrencyCode },
                Sequence = accountInfo.AccountData.Sequence,
            };
```
But it not work

**Comment by dangell7** [comment]
Did you get this to work?

**Comment by Platonenkov** [comment]
> Did you get this to work?

Yeah, I got it...
Working with trustlines is terrible..
Do you want me to tell ?

to decrypt flags, I had to write an extension, sometimes flags come that just do not decrypt

[EmumExtensions.cs](https://github.com/Platonenkov/xrpl.CSharp/blob/dev/Xrpl.C/Xrpl/Client/Extensions/EmumExtensions.cs)

**Comment by dangell7** [comment]
Yeah technically that should be in the binary parser but I would guess that functionality is missing.

This will definitely help others.

**Comment by Platonenkov** [comment]
the documentation does not contain complete information about deleting the trustline.
All that is written - the number of coins should be = 0, the limit = 0, and return the account to its original state.

but there is no information which original it is...

that is, we need to get information about the account from the server and check its settings (flag), if we received the flag = 0, then we need to send the default flag (SetNoRipple)..., or set flag from account

but there is one nuance:
when requesting trustines, we get not only our trustines, but also ltrustines established by others in relation to us, and it would be nice to filter these trustines, because they cannot be deleted.

but I'm didn't test with not default flag...
https://xrpl.org/accountroot.html#accountroot-flags


UDP: 
if you want to set a trustline in default state, the only important account flag is the "Default Ripple" flag (lsfDefaultRipple) this is the only one that really matters for your trustline
so you have to check:
1. if this flag is set
if set, the default state of your TL is "no_ripple: false" 
if the flag is NOT set, then default state of the "not_ripple" flag is "true"
(no ripple flag = flag of your trustline) 

```C#
            var accountInfo = await Client.AccountInfo(AccountSender);

            var flag = TrustSetFlags.tfSetNoRipple;
            if (accountInfo.AccountData.Flags != 0)
                flag = accountInfo.AccountData.Flags.HasFlag(AccountRootFlags.lsfDefaultRipple) ? TrustSetFlags.tfSetNoRipple : TrustSetFlags.tfClearNoRipple;

            ITrustSetTransaction trustSet = new TrustSetTransaction()
            {
                Flags = flag,
                Account = AccountSender,
                LimitAmount = new Currency { Value = "0", Issuer = Issuer, CurrencyCode = CurrencyCode },
                Sequence = accountInfo.AccountData.Sequence,
                Fee = await Client.GetMinimalFee(),

            };

            var json = trustSet.ToJson();
            var signer = TxSigner.FromSecret(AccountSecret);
            var signedTx = signer.SignJson(JObject.Parse(json));

            var request = new SubmitBlobRequest
            {
                TransactionBlob = signedTx.TxBlob
            };

            var result = await Client.SubmitTransactionBlob(request);

```

**Comment by dangell7** [comment]
Nice, I would also note, that if following the best practices, the account that "isssues" the asset is going to have trustlines "IN" where your personal will likely have trustlines "OUT".

So it would be less likely to have both INs and OUTs on one account, but it can happen. 

Also, if you want the trustlines for the issuing account, I would use gateway balances, and then account_lines for the regular accounts. 

However, if you're building like an explorer or something then I can see your reasoning.

**Comment by dangell7** [comment]
Finally, maybe I don't understand the use case but you can just override the flags on the TrustSet. I don't think that check above in necessary. If you are doing this for your own token, I just set the noRippledFlag and it works well.

Is default rippled would be set by the issuer of a token and they would very very rarely add a trustline for another token.
