### ISSUE TITLE
send non-XRP coin  (Question)

### ISSUE THREAD

**Issue by Platonenkov** [CASL-AE/xrpl.c#25]
help figure it out, in the test network I send the coin `FOO` `rPdDuRCGHLkMM7jSzo93CAjtniYiLEjBnL`
and I get an error 
![image](https://user-images.githubusercontent.com/44946855/183243983-496aa704-dac2-428c-a7b1-7ce59c08f717.png)

json
![image](https://user-images.githubusercontent.com/44946855/183243994-91b08cce-36c1-4d73-b5b3-7d5ba6290360.png)
can't understand

**Comment by dangell7** [comment]
Remove send max maybe?

<img width="1215" alt="Screen Shot 2022-08-06 at 7 49 44 AM" src="https://user-images.githubusercontent.com/25502424/183247762-cf3a5441-f2e3-4999-a7ee-15b817395dc4.png">

You're still "Issuing the token" imo.

<img width="1451" alt="Screen Shot 2022-08-06 at 7 52 50 AM" src="https://user-images.githubusercontent.com/25502424/183247857-381fa1d6-accc-498a-aad2-71e5311e0963.png">

**Comment by Platonenkov** [comment]
it seems that this was a token problem in the test network, it could not be forwarded..
in the main network all ok
