### ISSUE TITLE
TrustSet limit amount error

### ISSUE THREAD

**Issue by Platonenkov** [CASL-AE/xrpl.c#28]
the number of tokens in the network is defined in float,
why do we use UInt64?
![image](https://user-images.githubusercontent.com/44946855/186519214-0491ecc2-6bee-4ef0-8b63-0a57895cec4e.png)
![image](https://user-images.githubusercontent.com/44946855/186520027-0ba9ded6-7012-42e8-a6a2-8aa9608d844f.png)

**Comment by Platonenkov** [comment]
I checked decimal max value, it does not miss it either

**Comment by dangell7** [comment]
Amounts a represented as UInt64 on the ledger and parsed in the binary as such. We might need to make a helper function to "format" that for the user.

**Comment by Platonenkov** [comment]
> UInt64

but maximum of UInt64 is less than 5.0079845628115E+27, I do not understand...

**Comment by Platonenkov** [comment]
fixed https://github.com/Transia-RnD/xrpl.c/pull/34
