### ISSUE TITLE
Rename Repository and clean namespaces

### ISSUE THREAD

**Issue by dangell7** [CASL-AE/xrpl.c#37]
We need to rename the repository in v2. I'm open to suggestions. Currently the repo/solution name is `XRPL.C`. This isn't correct for C# so the namespace becomes `xrpl_c`. I then renamed the namespace to `Xrpl`. Its very messy.

Discussion:

The other repos are `xrpl.js`, `xrpl-py`, `XRPLSwift`, and `XRPL.C`

So maybe `XrplC` without the period or `XrplCSharp`?

Tasks: 

- [x] Rename Repository
- [x] Clean Namespaces
- [ ] Clean cproj file

**Comment by dangell7** [comment]
@Platonenkov

**Comment by Platonenkov** [comment]
I think `XrplCsharp`, because you may need to release in `C` too

**Comment by dangell7** [comment]
> I think `XrplCsharp`, because you may need to release in `C` too

Love it.
