### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dangell7** [CASL-AE/xrpl.c#38]
The repo needs to be documented. Every file in the repo also needs to, and likely already includes the link to the js repo that it has been ported from at the top of the file.

- [x] AddressCodec
- [x] BinaryCodec (IGNORE)
- [x] Keypairs (IGNORE the signing algorithms)
- [x] Xrpl/Client
- [x] Xrpl/Wallet
- [x] Generate into html

> For functions that are not documented in the js repo please just tag with a TODO and continue. If you can create some documentation based on what you see, please tag it with REVIEW so I know that its not documentation from another xrpl sdk.

**Comment by dangell7** [comment]
@Platonenkov

**Comment by Platonenkov** [comment]
ok
