### ISSUE TITLE
Client doesn't connect

### ISSUE THREAD

**Issue by sethnejame** [CASL-AE/xrpl.c#80]
I cloned this library to use in conjunction with a very simple .NET 6 console app to start experimenting with the ledger, but the websocket implementation doesn't work for me. Maybe I'm doing something wrong?

Specifically, I am injecting the IXrplClient class into my NetworkService class wrapper using standard DI via constructor.  Then I call the connect method in the class' GetAccountInfo method, all good.  And then I follow the connection flow through IXrplClient => connection => WebSocketClient.cs.  The code fails inside the ConnectAsync method of WebSocketClient.cs.

I debugged into the decompiled ClientWebSocket class to the ConnectAsync method and it seems the code freezes in this method:
`public Task ConnectAsync(Uri uri, CancellationToken cancellationToken)
    {
      if (uri == (Uri) null)
        throw new ArgumentNullException(nameof (uri));
      if (!uri.IsAbsoluteUri)
        throw new ArgumentException(SR.net_uri_NotAbsolute, nameof (uri));
      if (uri.Scheme != "ws" && uri.Scheme != "wss")
        throw new ArgumentException(SR.net_WebSockets_Scheme, nameof (uri));
      switch ((ClientWebSocket.InternalState) Interlocked.CompareExchange(ref this._state, 1, 0))
      {
        case ClientWebSocket.InternalState.Created:
          this.Options.SetToReadOnly();
          return this.ConnectAsyncCore(uri, cancellationToken);
        case ClientWebSocket.InternalState.Disposed:
          throw new ObjectDisposedException(this.GetType().FullName);
        default:
          throw new InvalidOperationException(SR.net_WebSockets_AlreadyStarted);
      }
    }`

The method freezes when we hit the switch statement, nothing happens, and eventually (after about 30 seconds or so) we get a `NotConnectedException` thrown.

I'm pretty sure I've got everything configured correctly, I register the client in my Program.cs like so:
`services.AddSingleton<IXrplClient>(provider =>
                    {
                           var uri = "wss://s.altnet.rippletest.net:51233";
                           return new XrplClient(uri);
                    });`

Not sure what I'm doing wrong here, any feedback would be appreciated.

**Comment by dangell7** [comment]
@sethnejame I updated the readme and I added the samples here.

https://github.com/Transia-RnD/XrplCSharp/blob/main/Tests/TestsClients/Test.ClonsoleApp/Program.cs

Let me know if you still have trouble

**Comment by sethnejame** [comment]
@dangell7 I'll have a look, thanks for getting back to me!
