### ISSUE TITLE
No nuget package found for this.

### ISSUE THREAD

**Issue by anilbx** [CASL-AE/xrpl.c#81]
[XrplCSharp](https://www.nuget.org/packages/XrplCSharp/)

showing 404

**Comment by sethnejame** [comment]
I had to clone the library and add a reference to it from my current console app.  But even then, the websocket implementation is broken.  It looks like the last time someone was active here was months ago, might have been they are busy with other stuff or are no longer maintaining the project.  The documentation is all wrong also.

**Comment by dangell7** [comment]
Hello, 

Yes, XrplCSharp has not been published. The old version is published under `xrpl.c` but there has been a huge refactor since then. 

I will work on publishing the new package `v2` this week.

**Comment by dangell7** [comment]
https://www.nuget.org/packages/XrplCSharp/
