### ISSUE TITLE
urls starting with "http[s]"  not accepted (and seems are not validated)

### ISSUE THREAD

**Issue by allende** [CASL-AE/xrpl.c#83]
Hi

I was testing the client and noticed after some trials that server urls will work only with "wss", not http/https, seems the code that validates them will return true no matter the string is passed to the client constructor, am I understanding wrong ? or is expected the wss url validation be performed by the dev ?
```

        public bool IsValidWss(string server)
        {
            return true;
        }

```

I used "http" instead of "wss" because I was actually reading an example from the python library, but later noticed that detail on the .NET sample, got me confused because the client was not throwing any error/result

Thank you,  didnt know a .NET libreary for the XRPL was already available, I'm just poking around with it.

**Comment by dangell7** [comment]
@allende Thanks for catching this. Yes, this client is only for websockets. Do you have a specific use case for rpc?

**Comment by allende** [comment]
Hi, no, I dont have any specific use case, and honestly barely know the difference between those terms at the technical level (you just gave me some homework to read tonight), as mentioned just was poking around with the library but copied the url from a python sample which was using http instead of wss and got stucked for a while until noticed that.

The testclient sample I wrote didn't return any error when passing the http url, as I was only trying to connect and didnt write any code to listen for OnError event, so just got me confused , then dig a bit into the code and realize that I have to use wss and the isValidWss will return true regardless of the string being passed. 

Not sure if some validation is worth it (like at checking the string starts with "wss" or something alike) neither if this may be considered a bug but was looking for some help-confirmation on my understanding.

thank you.

**Comment by dangell7** [comment]
Yeah I'm going to fixup `isValidWss` so I appreciate the error. 

You can just replace the http with wss and you should be good with most servers. (Some servers that you connect to might not be running ws but most will). This repo works a little differently than a "websocket". Basically it sends the request and waits for the response. So it "feels" like a normal api call and not a web socket. Then if you need the websocket, its available using the same client.

Thank you for using this library. There is a console program [here](https://github.com/Transia-RnD/XrplCSharp/blob/main/Tests/TestsClients/Test.ClonsoleApp/Program.cs) with some examples.
